### PR TITLE
Remove dependency in `fringe-helper.el`

### PR DESCRIPTION
**Pull request by DevelopmentCool2449**
fringe-helper is very outdated, i've changed the fringe definitions to something more built-in

### CODE REVIEW

**Comment by jcs090218** [comment]
You might want to remove the dependency from the package main file too.

**Comment by DevelopmentCool2449** [comment]
> You might want to remove the dependency from the package main file too.

Done. sorry i forgot about that

**Review by jcs090218 — APPROVED** [review]
Thank you!

**Comment by jcs090218** [comment]
I have a question regarding fringe-helper. 🤔 Why it's considered outdated? I've been using it for a few years and have no problem. Thanks!

**Comment by DevelopmentCool2449** [comment]
> I have a question regarding fringe-helper. 🤔 Why it's considered outdated? I've been using it for a few years and have no problem. Thanks!

The last fringe-helper update was 10 years ago and seems to be a bit abandoned, according to their repository there still 2 issues and 1 PR open like more than 3 or 4 years ago.

It can be a problem if there could be an incompatible change to fringes definitions.

**Comment by jcs090218** [comment]
I got it; thanks for your explanation! :)

**Pull request merged**
